builtin_models:
  - id: leeclaw-deepseek-default
    type: KnowledgeQA
    source: remote
    is_default: true
    name: ${LLM_MODEL_NAME}
    parameters:
      base_url: ${LLM_BASE_URL}
      api_key: ${LLM_API_KEY}
      provider: deepseek
      context_window: 128000

  - id: leeclaw-embedding-default
    type: Embedding
    source: remote
    is_default: true
    name: ${EMBEDDING_MODEL_NAME}
    parameters:
      base_url: ${EMBEDDING_BASE_URL}
      api_key: ${EMBEDDING_API_KEY}
      provider: siliconflow
      embedding_parameters:
        dimension: 1024
        truncate_prompt_tokens: 0
